name: Deploy to AWS Elastic Beanstalk

on:
  push:
    paths:
      - 'springboot-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Corretto JDK 17
      run: |
        wget -O- https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz | sudo tar xz -C /opt
        sudo update-alternatives --install /usr/bin/java java /opt/amazon-corretto-17.0.2.7.1-linux-x64/bin/java 1
        java -version

    - name: Build with Maven
      run: mvn -B package --file springboot-backend/pom.xml

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: NLP
        environment_name: NLP-env
        version_label: ${{ github.run_id }}
        region: ${{ secrets.AWS_REGION }}
        source_bundle: springboot-backend/target/springboot-backend-0.0.1-SNAPSHOT.jar
