name: Deploy to AWS Elastic Beanstalk

on:
  push:
    paths:
      - 'springboot-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file springboot-backend/pom.xml

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: NLP
        environment_name: NLP-env
        version_label: ${{ github.run_id }}
        region: ${{ secrets.AWS_REGION }}
        source_bundle: springboot-backend/target/springboot-backend-0.0.1-SNAPSHOT.jar
